spring.application.name=file-reader
server.port:8585

#For Multipart File Handle
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB
# optional: fail early before processing
spring.servlet.multipart.resolve-lazily=true
