spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ppldb
    driver-class-name: org.postgresql.Driver
    username: ppl_user
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate   # never update in prod
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: OFF

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
